language: python

python:
  - 3.6
  - 3.7

services: postgresql

env:
  - DJANGO=3.0.4

before_install:
  - export DJANGO_SETTINGS_MODULE=Bass.settings
  - export PYTHONPATH=$HOME/builds/pedobearbn21/Bass
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py runserver
