# Generated by Django 3.0.3 on 2020-03-03 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200225_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['at_time']},
        ),
        migrations.AlterModelOptions(
            name='stackcomment',
            options={'ordering': ['at_time']},
        ),
        migrations.RemoveField(
            model_name='stackcomment',
            name='stack',
        ),
        migrations.AddField(
            model_name='comment',
            name='at_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='stackcomment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='stackcomment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterModelTable(
            name='stackcomment',
            table='Stack_Comment',
        ),
    ]
