# Generated by Django 3.0.3 on 2020-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200303_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(1, True), (2, False)], default=1),
        ),
    ]
