# Generated by Django 3.0.4 on 2020-03-12 10:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_auto_20200308_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('video', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('at_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at_time'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StackComment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
